version: '3.3'
services:
  db:
    container_name: db
    image: mysql:latest
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    command: redis-server --requirepass superpassword
    ports:
      - 6379:6379
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    restart: always
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  waitress:
    platform: linux/amd64
    image: waitress:1.0
    restart: always
    depends_on:
      - db
      - kafka
    ports:
      - "9999:8080"
  chef:
    platform: linux/amd64
    image: chef:1.0
    restart: always
    depends_on:
      - db
      - kafka
    ports:
      - "9998:8080"
  cashier:
    platform: linux/amd64
    image: cashier:1.0
    restart: always
    depends_on:
      - db
      - kafka
    ports:
      - "9996:8080"

