server:
  port: 8080
spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://db:3306/restaurant?createDatabaseIfNotExist=true
    name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

kafka:
  server: kafka:9092
  offset-reset: latest
  topics:
    new: new.topic
    cook: cook.topic
  groupId:
    new: group.new.topic



